src/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="accounts"

urlpatterns=[
    path('signup/',views.signup,name="signup"),
    path('<slug:slug>/',views.profile,name="profile"),
]

src/product/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="product"

urlpatterns=[
    path('',views.product_list,name="products"),
    path('<slug:slug>/',views.product_detail,name="product_detail"),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('product.urls',namespace="main")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace="accounts")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
from django_countries.fields import CountryField
import datetime
from django.db.models.signals import post_save
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    slug = models.SlugField(blank=True,null=True)
    country =CountryField()
    img = models.ImageField(upload_to="profile_imgs",blank=True,null=True)
    address = models.CharField(blank=True, max_length=100)
    joindate = models.DateTimeField(blank=True, default=datetime.datetime.now)

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.user.username)
        super(Profile,self).save(*args,**kwargs)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('accounts:profile_detail',kwargs={'slug':self.slug})

def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile=Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)

src/product/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
import datetime
# Create your models here.
class Product(models.Model):
    name = models.CharField(blank=True, max_length=100)
    category=models.ForeignKey('Category',on_delete=models.CASCADE,blank=True,null=True)
    slug = models.SlugField(blank=True,null=True)
    brand=models.ForeignKey('settings.Brand',on_delete=models.CASCADE,blank=True,null=True)
    description = models.TextField(blank=True)
    img= models.ImageField(upload_to="product_img",blank=True,null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount= models.DecimalField(max_digits=6, decimal_places=2)
    cost = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateTimeField(blank=True, default=datetime.datetime.now)
    new = models.BooleanField(default=True)
    bestseller = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('main:product_detail',kwargs={'slug':self.slug})
    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'



    def save(self,*args,**kwargs):
        if not self.slug :
            self.slug=slugify(self.name)
        super(Product,self).save(*args,**kwargs)
    def __str__(self):
        return str(self.name)



class ProductImage(models.Model):
    image_product=models.ForeignKey(Product,on_delete=models.CASCADE)
    product_img= models.ImageField(upload_to="product_img")
    class Meta:
        verbose_name = 'ProductImage'
        verbose_name_plural = 'ProductImages'

    def __str__(self):
        return str(self.image_product)

class Category(models.Model):
    cat_name= models.CharField(blank=True, max_length=100)
    cat_parent=models.ForeignKey('self',blank=True,null=True,limit_choices_to={'cat_parent__isnull':True},on_delete=models.CASCADE)
    cat_description = models.TextField(blank=True)
    cat_img = models.ImageField(upload_to="category_img")
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return str(self.cat_name)

class Alternative(models.Model):
    alt_product=models.ForeignKey(Product,on_delete=models.CASCADE,related_name="main_product")
    alts= models.ManyToManyField(Product,related_name="alternative_products")

    class Meta:
        verbose_name = 'Alternative'
        verbose_name_plural = 'Alternatives'

    def __str__(self):
        return str(self.alt_product)

class Accessories(models.Model):
    acc_product=models.ForeignKey(Product,on_delete=models.CASCADE,related_name="master_product")
    accessories=models.ManyToManyField(Product,related_name="accessories_products")
    class Meta:
        verbose_name = 'Accessories'
        verbose_name_plural = 'Accessoriess'

    def __str__(self):
        return str(self.acc_product)

src/settings/models.py
from django.db import models

# Create your models here.
class Brand(models.Model):
    brand_name=models.CharField(blank=True, max_length=100)
    brand_desc=models.TextField(blank=True)
    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'

    def __str__(self):
        return str(self.brand_name)

class Variant(models.Model):
    var_name=models.CharField(blank=True, max_length=100)
    var_desc=models.TextField(blank=True)
    class Meta:
        verbose_name = 'Variant'
        verbose_name_plural = 'Variants'

    def __str__(self):
        return str(self.var_name)

src/accounts/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model= models.Profile
        fields=['img','country','address']

src/accounts/views.py
from django.shortcuts import render ,redirect , get_object_or_404
from django.contrib.auth.forms import UserCreationForm ,PasswordChangeForm
from .models import Profile
from django.contrib.auth import login ,authenticate
from .forms import UserForm ,ProfileForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def signup(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username =form.cleaned_data.get('username')
            password =form.cleaned_data.get('password1')
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('/')

    else:
        form=UserCreationForm()
    context={"form":form}
    return render(request,'registration/signup.html',context)

@login_required(login_url='/accounts/login')
def profile(request,slug):
    profile=get_object_or_404(Profile,slug=slug)
    context={"profile":profile}
    return render(request,'profile_detail.html',context)

src/product/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator

from.models import Product

# Create your views here.


def product_list(request):
    products=Product.objects.all()
    paginator = Paginator(products, 4)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    context={'products':products}
    return render(request,'Product/product_list.html',context)

def product_detail(request,slug):
    product=get_object_or_404(Product,slug=slug)
    context={'product':product}
    return render(request,'Product/product_detail.html',context)

src/settings/views.py
from django.shortcuts import render

# Create your views here.

src/accounts/templates/profile_detail.html
{% extends "base.html" %}

{% block body %}
{% load static %}
<div class="container my_naved">
  <div class="row cico mt-5">
    <div class="cico">

      <div class="col-md-12">
        {% if profile.img %}
          <img class="imgo_hei profile_img" src="{{profile.img.url}}"  alt="Card img cap">
        {% else %}
          <img src="{% static 'img/sample.jpg' %}" class="kool_img img-fluid" alt="">
        {% endif %}
      </div>
      <div class="col-md-12 profile_info">
        <h2>{{profile}}</h2>
        <h4>{{profile.user.email}}</h4>
        <h4>{{profile.country}}</h4>
        <h4>{{profile.address}}</h4>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="container mt-5 mb-5">
  <div class="row mt-5">
    <h2 class="p-2 btn-secondary">My Orders</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Order number</th>
          <th scope="col">Total</th>
          <th scope="col">Type</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
{% endblock body%}

src/product/templates/Product/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block body %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          {% if product.img %}
          <img src="{{product.img.url}}" class="kool_img img-fluid" alt="">
          {% else %}
          <img src="{% static 'img/sample.jpg' %}" class="kool_img img-fluid" alt="">
          {% endif %}

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{product.category}}</span>
              </a>
              {% if product.discount > 0 %}
              <a href="">
                <span class="badge green mr-1">Sale</span>
              </a>
              {% endif %}
              {% if product.new %}
                <a href="">
                  <span class="badge red mr-1">New</span>
                </a>
              {% endif %}

              {% if product.bestseller %}
                <a href="">
                  <span class="badge blue mr-1">Bestseller</span>
                </a>
              {% endif %}

            </div>
            <p class="lead font-weight-bold">{{product.name}}</p>

            {% if product.discount > 0 %}
              <p class="lead">
                <span class="mr-1">
                  <del>{{product.price}}</del>
                </span>
                <span>{{product.discount}}</span>
              </p>
            {% else %}
              <p class="lead">
                <span>{{product.price}}</span>
              </p>
            {% endif %}
            <p class="lead font-weight-bold">Description</p>

            <p>{{product.description}}</p>

            <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Accessories</h4>


        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">
          <h4 class="my-4 h4">Accessories</h4>

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">
          <h4 class="my-4 h4">Accessories</h4>

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">
          <h4 class="my-4 h4">Accessories</h4>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock body %}

src/product/templates/Product/product_list.html
{% extends "base.html" %}
{% block body %}
  <!--Main layout-->
  {% load static %}
  <main class="mt-5">
    <div class="container my_naved">

      <!--Navbar-->
      <nav class="navbar nav_set navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mt-5 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for product in products  %}

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              {% if product.img %}
              <div class="view overlay ">
                <img src="{{product.img.url}}" class="imgo_hei card-img-top"
                  alt="">
                {% else %}
                <img src="{% static 'img/sample.jpg' %}" class="imgo_hei card-img-top"
                  alt="">
                {% endif %}
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{product.category}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{product.get_absolute_url}}" class="dark-grey-text">{{product.name}}
                      <p>
                        {% if product.new %}
                          <span class="badge badge-pill danger-color">NEW</span>
                        {% endif %}
                        {% if product.discount > 0 %}
                        <a href="">
                          <span class="badge green mr-1">Sale</span>
                        </a>
                        {% endif %}
                      </p>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>{{product.price}}</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}

        </div>
      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if products.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          {% for page in products.paginator.page_range %}
            <li class="page-item active">
              <a class="page-link" href="?page={{page}}">{{page}}
              </a>
            </li>
          {% endfor %}

          {% if products.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
{% endblock body %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>SouqStore</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">

  <link href="{% static 'css/mina.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar mb-50">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/" >
        <strong class="blue-text">SouqStore</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/" target="_blank">Category</a>
          </li>

        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          {% if user.is_authenticated %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle fas fa-user-alt " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profile page</a>
          <a class="dropdown-item" href="#">Edit my Profile</a>
          <a class="dropdown-item" href="#">Change Password</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">my orders</a>
          <a class="dropdown-item" href="#">track order</a>
        </div>
      </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'login'%}" class="nav-link border border-light rounded waves-effect">
              <i class="fas fa-sign-in-alt"></i>LOGIN
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'accounts:signup'%}" class="nav-link border border-light rounded waves-effect">
              <i class="fas fa-user-plus"></i>SIGNUP
            </a>
          </li>
          {% endif %}

        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->


  <!--Main layout-->
{% block body %}

{% endblock body %}
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
        role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>